---
name: Docker Image CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker images
          docker system info
    permissions:
      id-token: write
      attestations: write
      contents: read

    
